name: Sample workflow
on:
  workflow_dispatch:
    inputs:
      terraform-folder-sandbox:
        description: 'Folder where the terraform code for dev environment resides'
        required: true
        default: 'infra/environments/dev'
env:
  TF_FOLDER_SANDBOX: ${{ github.event.inputs.terraform-folder-sandbox }}
jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Initialize, Plan and Apply
        run: |
          terraform version
          terraform init
          terraform plan
          terraform apply -auto-approve
        working-directory: $TF_FOLDER_SANDBOX
