name: Sample workflow
on:
  push:
    branches:
      - main
env:
  SANDBOX: 'infra/environments/dev'
jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Initialize, Plan and Apply
        run: |
          pwd
          terraform version
          terraform init
          terraform plan
          terraform apply -auto-approve
        working-directory: ${{ env.SANDBOX }}
